### ISSUE TITLE
Fetching data from mongo DB after first data pass

### ISSUE THREAD

**Issue by jacomoel** [SpiffiRacoon/ISBiT#43]
Implement function to access data after the first time users have done manual labeling (pass1). 

I am not sure about the architecture for this but we somehow need to add this to the system. 

- **Is this part of the ML lib? (some getter used in latter_run() function)**

**Comment by jacomoel** [comment]
It might be wise to wait with this issue for the frontend-team to be done with architecture/design of how to pass data back after user interaction.

**Comment by Leohemmingsson** [comment]
This is also blocked by #31 
This issue should be easy to implement when the versioning is done

**Comment by jacomoel** [comment]
this issue is replace by #75 , closing this one
